config_version = 14

[bar.default]
background_opacity = 0.44999998994171619
end = [
    "media",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "session"
]
reserve_space = false
smart_auto_hide = true

[calendar]
enabled = true

    [calendar.account.personal_google]
    type = "google"

[hooks]
shutting_down = "~/bin/sys/0-pre-shutdown.sh"

[keybinds]
down = [ "Down", "Ctrl+j", "Ctrl+p" ]
left = [ "Left", "Ctrl+l" ]
right = [ "Right", "Ctrl+h" ]
up = [ "Up", "Ctrl+k", "Ctrl+n" ]

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
background_opacity = 0.44999998994171619
position = "top_center"

[osd]
background_opacity = 0.44999998994171619

[plugin_settings."remo/noctes"]
save_path = "/home/davidn/Documents/Noctes-notes"

[plugins]
enabled = [ "remo/noctes", "yocraft/web-launcher", "dotnetrob/cat", "alexander/game-launcher" ]

[shell]
avatar_path = "/home/davidn/Pictures/Beibis/IMG-20260622-WA0001.jpg"
font_family = "JetBrainsMono Nerd Font Propo"
niri_overview_type_to_launch_enabled = true
settings_window_translucent = true

    [shell.greeter_sync]
    auto_sync = true

    [shell.panel]
    clipboard_placement = "attached"

[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

[wallpaper.default]
path = "/home/davidn/Pictures/Wallpapers/Mios/IMG_0109.png"

[wallpaper.last]
path = "/home/davidn/Pictures/Wallpapers/Mios/IMG_0109.png"

[wallpaper.monitors.HDMI-A-1]
path = "/home/davidn/Pictures/Wallpapers/Mios/IMG_0109.png"