exec-once = hyprlock
exec-once = brightnessctl set 25%               # Incia con el brillo del portatil al 10% para no gastar bateria 
exec-once = hyprpaper                           # Inicia hyprpaper para establecer fondo de pantalla 
exec-once = shikane                             # Inicia shikane para desactiva monitor poratil cuando se conecta uno externo
exec-once = systemctl --user restart pipewire   # para fixear el bluetooth parece que se jode por pipewire
exec-once = swaync                              # Inica swaync notification daemon
exec-once = waybar
