
############################
### PROGRAMS & AUTOSTART ###
############################

exec-once = mega-cmd-server                     # Inica mega-cmd-server para utilizar sincronización de mega al realizar cambios 
exec-once = brightnessctl set 10%               # Incia con el brillo del portatil al 10% para no gastar bateria 
exec-once = hyprpaper                           # Inicia hyprpaper para establecer fondo de pantalla 
exec-once = shikane                             # Inicia shikane para desactiva monitor poratil cuando se conecta uno externo
exec-once = systemctl --user restart pipewire   # para fixear el bluetooth parece que se jode por pipewire
exec-once = swaync                              # Inica swaync notification daemon
