###############################################################################
# Prefix Configuration
###############################################################################

# Set prefix to backtick (`)
set -g prefix `
unbind C-b
bind ` send-prefix

###############################################################################
# Vim-style Keybinds
###############################################################################

# Enable vi mode for copy/paste
set-window-option -g mode-keys vi

# Vim-like pane navigation (no prefix needed)
bind -n C-h select-pane -L  # Move left
bind -n C-j select-pane -D  # Move down
bind -n C-k select-pane -U  # Move up
# Note: C-l is reserved for clear-screen

# Vim-like copy mode bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

# Fix wl-clipboard
set -g @yank_action 'copy-pipe-and-cancel "wl-copy"'
set -g @yank_selection 'clipboard'
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

###############################################################################
# Window/Pane Management
###############################################################################

# Splits (modified from default " and %)
bind v split-window -v -c "#{pane_current_path}"  # Vertical split
bind b split-window -h -c "#{pane_current_path}"  # Horizontal split

# Windows
bind c new-window -c "#{pane_current_path}"  # New window
bind x kill-window                           # Kill window

# Panes
bind & kill-window
bind x kill-pane

###############################################################################
# Session Management
###############################################################################

# <leader> + Shift + c creates a new session
bind C command-prompt -p "New Session:" "new-session -A -s '%%'"
# <leader> + Shift + x deletes current session
bind K confirm kill-session


###############################################################################
# Custom Binds
###############################################################################

# Enter copy mode with ` + m (instead of ` + [)
bind m copy-mode

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded"


###############################################################################
# Tmux Session Managment
###############################################################################

# set -g @resurrect-save "S"
# set -g @resurrect-restore "R"
# set -g @continuum-restore "on"
# set -g @resurrect-strategy-nvim "session"
# set -g @resurrect-capture-pane-contents "on"

