
# Fix tmux-yank to be more vim like 
# Set vi mode
set-window-option -g mode-keys vi 

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection 
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel


# Configurar las teclas vim para moverse entre paneles
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Quitar confirmación de eliminación ventana
bind-key & kill-window
# Fixear confirmación kill-pane
bind-key x confirm-before -p "kill-pane #W? (y/n)" kill-pane

# Set split launch current path on split pane
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Binds interesantes
# Opción 1: Usar bind-key con la flag -n para no requerir prefix
bind-key -n C-l send-keys C-l

# Opción 2: Agregar una regla específica para el modo root
bind -T root C-l send-keys C-l

# Resourcear con C-a + r
bind r source-file ~/.config/tmux/tmux.conf \; display "Tmux config sourced"


