# Algunas configuraciones adicionales útiles
set -g base-index 1               # Empezar a contar las ventanas desde 1
setw -g pane-base-index 1        # Empezar a contar los paneles desde 1
set -g history-limit 10000       # Aumentar el límite del historial
set-option -g renumber-windows on # Reordena las ventanas de tmux tras eliminar otra.

# Mejorar los colores
set -g default-terminal "screen-256color"

# Reducir el delay al presionar ESC
set -sg escape-time 0


