# Cargar los colores de pywal
source ~/.cache/wal/colors.tmux

# Barra de estado - solo modos
set -g status on
set -g status-style "bg=#{@color0},fg=#{@color7}"  # Barra de estado más oscura
set -g status-justify "centre"
set -g status-left-length 90
set -g status-right-length 90

# Mostrar modos activos en la barra de estado
set -g status-left "#{tmux_mode_indicator}"
set -g status-right "#[fg=#{@color9},bg=#{@color6}] %H:%M #[fg=#{@color9},bg=#{@color7}] %d-%b-%y #[fg=#{@color8},bg=#{@bg}]"

# Indicadores de modo
set -g @mode_indicator_prefix_mode_style "bg=#{@color2},fg=#{@bg}"
set -g @mode_indicator_copy_mode_style "bg=#{@color4},fg=#{@bg}"
set -g @mode_indicator_sync_mode_style "bg=#{@color8},fg=#{@bg}"
set -g @mode_indicator_empty_mode_style "bg=#{@color7},fg=#{@bg}"

set -g @mode_indicator_prefix_prompt " WAIT "
set -g @mode_indicator_copy_prompt " COPY "
set -g @mode_indicator_sync_prompt " SYNC "

# Estado de las ventanas
setw -g window-status-format "#[fg=#{@color8},bg=#{@color0}] #I:#W "  # Ventana inactiva
setw -g window-status-current-format "#[fg=#{@fg},bg=#{@color0}] #I:#W "  # Ventana activa

