###############################################################################
# Tokyo Night Theme Configuration - Modificado con recuadros
###############################################################################

# Base Colors (Tokyo Night palette)
bg="#1a1b26"          # Main background
fg="#9299ba"          # Primary text color
accent="#7aa2f7"      # Active element highlight
inactive="#3b4261"    # Inactive pane borders
highlight="#24283b"   # For window backgrounds
green="#9ece6a" 

### Status Bar Configuration ###
set -g status on
set -g status-justify centre
set -g status-position bottom
set -g status-style "bg=$bg,fg=$fg"
set -g status-left-length 90
set -g status-right-length 90

# Window Styles
set -g window-style "fg=$fg,bg=$bg"
set -g window-active-style "fg=$fg,bg=$bg"

### Pane Border Configuration ###
set -g pane-border-style "fg=$inactive,bg=$bg"         # Inactive pane border
set -g pane-active-border-style "fg=$accent,bg=$bg"    # Active pane border 
setw -g pane-border-status off
set -g pane-border-lines single

### Mode Indicator
set -g @mode_indicator_prefix_mode_style "bg=$green,fg=$bg"
set -g @mode_indicator_copy_mode_style "bg=$accent,fg=$bg"
set -g @mode_indicator_sync_mode_style "bg=$inactive,fg=$bg"
set -g @mode_indicator_empty_mode_style "bg=$inactive,fg=$bg"

set -g @mode_indicator_prefix_prompt " WAIT "
set -g @mode_indicator_copy_prompt " COPY "
set -g @mode_indicator_sync_prompt " SYNC "
set -g @mode_indicator_empty_prompt " TMUX "


### Window Status Formatting  ###
setw -g window-status-separator " "
setw -g window-status-format "#[fg=$inactive,bg=$highlight] #I:#W "          # Inactive window
setw -g window-status-current-format "#[fg=$accent,bg=$highlight] #I:#W "    # Active window

### Status Line Content ###
set -g status-left "#{tmux_mode_indicator}"
set -g status-right "#[fg=$inactive,bg=$highlight] %H:%M #[fg=$accent,bg=$highlight] %d-%b-%y #[fg=$inactive,bg=$bg]"

### Message Display Style ###
set -g message-style "bg=$accent,fg=$bg"
set -g message-command-style "bg=$accent,fg=$bg"
