# Algunas configuraciones adicionales útiles
set -g mouse on                    # Habilitar el uso del mouse
set -g base-index 1               # Empezar a contar las ventanas desde 1
setw -g pane-base-index 1        # Empezar a contar los paneles desde 1
set -g history-limit 10000       # Aumentar el límite del historial
set-option -g renumber-windows on # Reordena las ventanas de tmux tras eliminar otra.

# Mejorar los colores
set -g default-terminal "screen-256color"

# Reducir el delay al presionar ESC
set -sg escape-time 0

# Quitar indicador de numerico de cada ventana de tmux
set -g window-status-format "#{window_name}"

# Quita el texto en la ventana activa
set -g window-status-current-format " "  # Ventana activa

# Quita el texto en las ventanas inactivas
set -g window-status-format " "  # Ventanas inactivas


# Set theme with tpm
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @plugin "tmux-plugin/tmux-yank"

# Tmux tokyo night theme config 
set -g @theme_transparent_status_bar 'true'
set -g @theme_plugins battery

# Fix tmux-yank to be more vim like 
# Set vi mode
set-window-option -g mode-keys vi 

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection 
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel


# Configurar las teclas vim para moverse entre paneles
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Set prefix 
# Despues de experimentar con varias configuraciones me decanto por Meta + Space, ya que tengo meta remapeado al Caps Lock luego es el 
#boton mas comodo como prefijo y la verdad va bastante feten considerando mi configuración de hyprland además de no tener ninguna 
#incompatibilidad con ningún programa 
unbind C-b
set -g prefix M-space	
bind M-space send-prefix

# Quitar confirmación de eliminación ventana
bind-key & kill-window
# Fixear confirmación kill-pane
bind-key x confirm-before -p "kill-pane #W? (y/n)" kill-pane

# Set split launch current path on split pane
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Binds interesantes
# Opción 1: Usar bind-key con la flag -n para no requerir prefix
bind-key -n C-l send-keys C-l

# Opción 2: Agregar una regla específica para el modo root
bind -T root C-l send-keys C-l

# Resourcear con C-a + r
bind r source-file ~/.config/tmux/tmux.conf \; display "Tmux config sourced"

run "~/.tmux/plugins/tpm/tpm"
