#######################
### GENERAL SETTINGS ###
#######################

remember_window_size        yes
confirm_os_window_close     0
allow_remote_control        yes
hide_window_decorations     yes
macos_option_as_alt         no
background_opacity          0.8
term                        xterm-kitty

#######################
### FONT CONFIG ###
#######################

font_family                 MesloLGS Nerd Font Mono
italic_font                 auto
bold_font                   auto
bold_italic_font            auto
font_size                   16.0
adjust_line_height          115%
adjust_column_width         100%
symbol_map                  U+E0A0-U+E0A2,U+E0B0-U+E0B3 PowerlineSymbols

#######################
### CURSOR & SCROLL ###
#######################

cursor_shape                block
cursor_blink_interval       0.5
cursor_stop_blinking_after  15.0
scrollback_lines            9000
wheel_scroll_multiplier     5.0
scrollback_pager            less +G -R

# Funny setting
cursor_trail                1

#######################
### WINDOW & LAYOUT ###
#######################

# Reduced vertical padding (top/bottom)
window_padding_width        5 10 5 10  
enabled_layouts             *

#######################
### BELL & SOUND ###
#######################

visual_bell_duration        0.0
enable_audio_bell           no

#######################
### MOUSE & CLICKS ###
#######################

click_interval              0.5
mouse_hide_wait             0.0
select_by_word_characters   :@-./_~?&=%+#

#######################
### PERFORMANCE ###
#######################

repaint_delay               10
input_delay                 3

#######################
### URL HANDLING ###
#######################

open_url_modifiers          ctrl+shift
open_url_with               default

#######################
### KEY MAPPINGS ###
#######################

# Clipboard
map ctrl+shift+v            paste_from_clipboard
map ctrl+shift+s            paste_from_selection
map ctrl+shift+c            copy_to_clipboard
map shift+insert            paste_from_selection

# Font size
map ctrl+shift+up           increase_font_size
map ctrl+shift+down         decrease_font_size
map ctrl+shift+backspace    restore_font_size

#######################
### THEME ###
#######################

include                     current-theme.conf
