pulse.rules = [
    {
        matches = [ 
            { application.process.binary = "Discord" }
            { application.process.binary = "vesktop" }
        ]
        actions = { quirks = [ block-source-volume ] }
    }
]
