[[profile]]
name = "laptop builtin"

    [[profile.output]]
    search = ["eDP-1"]
    enable = true
    mode = "1920x1080@60Hz"
    exec = ["hyprctl keyword monitor eDP-1,1920x1080@60,0x0,1"]

[[profile]]
name = "no builtin + HDMI"

    [[profile.output]]
    search = ["eDP-1"] 
    enable = false
    exec = ["hyprctl keyword monitor eDP-1,disable"]

    [[profile.output]]
    search = ["HDMI-A-1"]
    enable = true
