# Setup
tmux_dir="$HOME/.config/tmux"
tmux_conf_dir="$tmux_dir/config"
tmux_plugins_dir="$tmux_dir/plugins"

# Configuration
source "$tmux_conf_dir/options.conf"
source "$tmux_conf_dir/keybinds.conf"
source "$tmux_conf_dir/theme.conf"

# Plugins
# Mode Indicator
# set -g @plugin "MunifTanjim/tmux-mode-indicator"
# not using tpm anymore, doesnt make sense to use it if i use only one polugin
run-shell ~/.config/tmux/tmux-mode-indicator/mode_indicator.tmux
