###############################################################################
# Setup
###############################################################################

tmux_dir="~/.config/tmux"
tmux_conf_dir="$tmux_dir/config"
tmux_plugins_dir="$tmux_dir/plugins"

###############################################################################
# Configuration
###############################################################################

source "$tmux_conf_dir/options.conf"
source "$tmux_conf_dir/keybinds.conf"
source "$tmux_conf_dir/theme.conf"

# Set theme with tpm
set -g @plugin "tmux-plugins/tpm"

# No me acuerdo que hace
set -g @plugin "tmux-plugin/tmux-yank"

run "~/.config/tmux/plugins/tpm/tpm"
