###############################################################################
# Setup
###############################################################################

tmux_dir="$HOME/.config/tmux"
tmux_conf_dir="$tmux_dir/config"
tmux_plugins_dir="$tmux_dir/plugins"

###############################################################################
# Configuration
###############################################################################

source "$tmux_conf_dir/options.conf"
source "$tmux_conf_dir/keybinds.conf"
source "$tmux_conf_dir/theme.conf"

###############################################################################
#Plugins
###############################################################################

# Tmux Plugin Manager
set -g @plugin "tmux-plugins/tpm"

# Enables yank on clipboard
set -g @plugin "tmux-plugin/tmux-yank"

# Sensible default values
set -g @plugin "tmux-plugins/tmux-sensible"

# Mode Indicator
set -g @plugin "MunifTanjim/tmux-mode-indicator"

# Restore tmux sessions
set -g @plugin "tmux-plugins/tmux-resurrect"

# Continuous saving of tmux environment - MUST BE LAST
set -g @plugin "tmux-plugins/tmux-continuum"

# To restore nvim session 
set -g @resurrect-strategy-nvim "session"

run "~/.config/tmux/plugins/tpm/tpm"
