#!/bin/bash

# Directorios y archivos
WALLPAPERS_DIR="$HOME/Pictures/Wallpapers/wall-randomizer"
DESTINATION="$HOME/Pictures/Wallpapers/hyprpaper-wall.png"
CACHE_DIR="$HOME/.cache/wal"
TEMPLATES_DIR="$HOME/.config/wal/templates"

# Cargar colores de pywal si existen para la previsualización
if [ -f "$CACHE_DIR/colors.sh" ]; then
  source "$CACHE_DIR/colors.sh"
else
  # Colores por defecto si no existe el archivo
  color0="#000000"  # background
  color15="#FFFFFF" # foreground
fi

# Crear archivo .Xresources con los colores de pywal para sxiv
echo "! X colors." > ~/.Xresources
echo "! Generated by 'wal'" >> ~/.Xresources
echo "*foreground: ${color15}" >> ~/.Xresources
echo "*background: ${color0}" >> ~/.Xresources
echo "Sxiv.foreground: ${color15}" >> ~/.Xresources
echo "Sxiv.background: ${color0}" >> ~/.Xresources

# Recargar tema previo a ejecución
xrdb -merge ~/.Xresources

# Iniciar swww si no está en ejecución
pgrep -x "swww" >/dev/null || { swww init & sleep 0.1; }

# Seleccionar wallpaper con sxiv
selected=$(sxiv -g 800x600+560+240 -b -t -o "$WALLPAPERS_DIR"/*.{jpg,jpeg,png,gif} 2>/dev/null)
[ -z "$selected" ] && exit 0

# Aplicar wallpaper con swww
{
  swww img "$selected" --transition-type grow --transition-pos 0.98,0.97 --transition-step 255 --transition-fps 60
} &

# Crear enlace o copiar para swww y navegador web
{
  # Directorio para el fondo del navegador web
  BROWSER_WALLPAPER_DIR="$HOME/Pictures/Wallpapers/web-browser-wallp"
  BROWSER_WALLPAPER="$BROWSER_WALLPAPER_DIR/web-wallpaper.png"

  # Crear directorio si no existe
  mkdir -p "$BROWSER_WALLPAPER_DIR"

  # Copiar al destino principal (para compatibilidad con otros scripts)
  if [[ "$selected" == *.gif ]]; then
    # Extraer el primer frame y guardar como PNG
    convert "$selected[0]" "$DESTINATION"
  else
    cp "$selected" "$DESTINATION"
  fi

  # Copiar para el navegador web (siempre como PNG para compatibilidad)
  if [[ "$selected" == *.gif ]]; then
    # Verificar si el archivo ya existe y eliminarlo primero para evitar duplicados
    [ -f "$BROWSER_WALLPAPER" ] && rm "$BROWSER_WALLPAPER"
    
    # Extraer el primer frame y guardar como PNG
    convert "$selected[0]" "$BROWSER_WALLPAPER"
  else
    # Si no es GIF, simplemente copiar, sobrescribiendo cualquier archivo existente
    cp -f "$selected" "$BROWSER_WALLPAPER"
  fi
} &

wait
