return {
	"folke/snacks.nvim",
	priority = 1000,
	lazy = false,
	opts = {
		picker = { enabled = true },
		explorer = { enabled = false },
		image = { enabled = false },
		indent = { enabled = true },
		notify = { enabled = true },
		notifier = { enabled = true },
		dashboard = { enabled = true },
		scroll = { enabled = true },
		bigfile = { enabled = true },
		input = { enabled = true },
		scope = { enabled = true },
		words = { enabled = true },
		statuscolumn = { enabled = true },
		quickfile = { enabled = true },
		lazygit = { enabled = true },
	},
}
