# System and service management
exec-once = systemctl --user restart pipewire   # Fix Bluetooth issues
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Display 
exec-once = swww-daemon

# User interface and utilities
exec-once = waybar
exec-once = swaync
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = /usr/bin/cliphist wipe

# Scripts and custom commands
exec-once = bash -c "/home/davidn/bin/services/sync-notes-loop.sh"
exec-once = bash -c "/home/davidn/bin/services/sync-keepass-loop.sh"
exec-once = /home/davidn/bin/ui/blue-light.sh

