##########################
### MY HYPRLAND CONFIG ###
##########################

# https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

source = ~/.config/hypr/hyprland-settings/monitors.conf   
source = ~/.config/hypr/hyprland-settings/autostart.conf
source = ~/.config/hypr/hyprland-settings/looknfeel.conf
source = ~/.config/hypr/hyprland-settings/input.conf
source = ~/.config/hypr/hyprland-settings/env-vars.conf
source = ~/.config/hypr/hyprland-settings/keybinds.conf
source = ~/.config/hypr/hyprland-settings/windows-workspaces.conf
source = ~/.config/hypr/hyprland-settings/looknfeel.conf


