preload = /home/davidn/Pictures/Wallpapers/hyprpaper-wall.png


wallpaper = eDP-1,/home/davidn/Pictures/Wallpapers/hyprpaper-wall.png
wallpaper = HDMI-A-1,/home/davidn/Pictures/Wallpapers/hyprpaper-wall.png


