#!/bin/bash
# Directorios
WALLPAPERS_DIR="$HOME/Pictures/Wallpapers/wall-randomizer"
DESTINATION="$HOME/Pictures/Wallpapers/hyprpaper-wall.png"

# Cargar colores de pywal si existen
if [ -f "$HOME/.cache/wal/colors.sh" ]; then
  source "$HOME/.cache/wal/colors.sh"
else
  # Colores por defecto si no existe el archivo
  color0="#000000"  # background
  color15="#FFFFFF" # foreground
fi

# Crear archivo .Xresources con los colores de pywal
echo "! X colors." > ~/.Xresources
echo "! Generated by 'wal'" >> ~/.Xresources
echo "*foreground: ${color15}" >> ~/.Xresources
echo "*background: ${color0}" >> ~/.Xresources
echo "Sxiv.foreground: ${color15}" >> ~/.Xresources
echo "Sxiv.background: ${color0}" >> ~/.Xresources

# Recargar tema previo a ejecución
xrdb -merge ~/.Xresources

# Listar todos los fondos
wallpapers=($(find "$WALLPAPERS_DIR" -type f \( -name "*.jpg" -o -name "*.png" -o -name "*.jpeg" \)))

# Verificar si hay fondos
if [ ${#wallpapers[@]} -eq 0 ]; then
  notify-send "Error" "No se encontraron fondos de pantalla"
  exit 1
fi

# Mostrar sxiv para seleccionar el fondo
selected=$(sxiv -g 800x600+560+240 -b -t -o "${wallpapers[@]}")

# Aplicar el fondo seleccionado si hay selección
if [ -n "$selected" ]; then
  killall -SIGKILL hyprpaper 2>/dev/null || true
  cp "$selected" "$DESTINATION"

  if [ ! -f "$DESTINATION" ]; then
    notify-send "Error" "No se pudo copiar el fondo de pantalla"
    exit 1
  fi

  /usr/bin/hyprpaper >/dev/null 2>&1 &
  notify-send "Fondo cambiado" "$(basename "$selected")"

  rm -rf ~/.cache/wal/*
  wal -i "$DESTINATION"

  tmux source-file ~/.config/tmux/tmux.conf
  notify-send "Colores de tmux cambiados"

  killall -SIGKILL waybar 2>/dev/null || true
  sleep 0.5
  /usr/bin/waybar >/dev/null 2>&1 &
  notify-send "Colores de Waybar cambiados"

  if pgrep -x "nvim" > /dev/null; then
    pkill nvim
    sleep 1
    nvim &
  fi
  notify-send "Colores de Neovim cambiados"

  # Cambiar tema de zathura
  colors=($(<~/.cache/wal/colors))

  cat > ~/.config/zathura/zathurarc <<EOF
  set selection-clipboard clipboard
  set adjust-open "fit-width"
  set pages-per-row 1
  set scroll-page-aware "true"
  set smooth-scroll "true"
  set scroll-full-overlap 0.01
  set scroll-step 100
  set guioptions none

  set default-bg                  "${colors[0]}"
  set default-fg                  "${colors[7]}"

  set statusbar-fg                "${colors[7]}"
  set statusbar-bg                "${colors[1]}"

  set inputbar-bg                 "${colors[0]}"
  set inputbar-fg                 "${colors[6]}"

  set notification-bg             "${colors[0]}"
  set notification-fg             "${colors[6]}"

  set notification-error-bg       "${colors[0]}"
  set notification-error-fg       "${colors[1]}"

  set notification-warning-bg     "${colors[0]}"
  set notification-warning-fg     "${colors[3]}"

  set highlight-color             "${colors[4]}"
  set highlight-active-color      "${colors[5]}"

  set completion-bg               "${colors[1]}"
  set completion-fg               "${colors[7]}"

  set completion-highlight-fg     "${colors[5]}"
  set completion-highlight-bg     "${colors[1]}"

  set recolor                     "true"
  set recolor-keephue             "false"
  set recolor-lightcolor          "${colors[0]}"
  set recolor-darkcolor           "${colors[7]}"
EOF

notify-send "Colores de Zathura cambiados"

  # Cursor de kitty
  cursor_color=$(sed -n '8p' "$HOME/.cache/wal/colors")
  dark_cursor=$(echo "$cursor_color" | awk -F'#' '{ 
  r = strtonum("0x" substr($2,1,2)) * 0.7;
  g = strtonum("0x" substr($2,3,2)) * 0.7;
  b = strtonum("0x" substr($2,5,2)) * 0.7;
  printf("#%02x%02x%02x\n", r, g, b);
}')

sed -i '/^cursor /d' "$HOME/.cache/wal/colors-kitty.conf"
echo "cursor $dark_cursor" >> "$HOME/.cache/wal/colors-kitty.conf"
notify-send "Cursor de kitty arreglado"

  # 🎨 Tema de Wofi
  cat > ~/.config/wofi/style.css <<EOF
  * {
    font-family: "JetBrainsMono Nerd Font", monospace;
  }

  window {
    background-color: ${colors[0]};
    border: none;
  }

    #input {
    margin: 5px;
    border-radius: 0px;
    border: none;
    background-color: ${colors[1]};
    color: ${colors[15]};
    padding: 8px;
  }

    #inner-box {
    background-color: ${colors[0]};
  }

    #outer-box {
    margin: 2px;
    padding: 10px;
    background-color: ${colors[0]};
  }

    #scroll {
    margin: 5px;
  }

    #text {
    padding: 4px;
    color: ${colors[6]};
  }

    #entry {
    background-color: ${colors[0]};
  }

    #entry:selected {
    background-color: ${colors[5]}; /* Color más neutro y visible */
    }

    #text:selected {
    color: ${colors[15]};  /* texto blanco */
    background: transparent;
    }

    #entry:hover {
    background-color: ${colors[2]};
  }
EOF

notify-send "Colores de Wofi actualizados"
notify-send "Paleta de colores cambiada"
fi

