# System and service management
exec-once = systemctl --user restart pipewire    # Fix Bluetooth issues
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Display and brightness settings
exec-once = brightnessctl set 30%
exec-once = swww-daemon


# monitor toggle
exec-once = shikane >> /tmp/shikane-session.log 2>&1

# User interface and utilities
# exec-once = swaync
exec-once = dunst
# Testing using notifications
# exec-once = waybar 
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = /usr/bin/cliphist wipe
exec-once = hyprctl setcursor Bibata-Modern-Classic 20
exec-once = mpc stop && hyprlock 


# Generate new music covers for use on hyprlock
exec-once = bash -c "/home/davidn/.config/hypr/bin/gen-art.sh"


# Scripts and custom commands
exec-once = bash -c "/home/davidn/bin/sys/init-power.sh"
exec-once = bash -c "/home/davidn/bin/sys/sync-git.sh ~/Documents/Obsidian/ ~/Documents/Keepass/ --loop"
exec-once = bash -c "/home/davidn/bin/sys/battery.sh"
exec-once = bash -c "/home/davidn/.config/hypr/bin/hyprsunset_config.sh"
exec-once = bash -c "/home/davidn/bin/services/mute-sound.sh"
# exec-once = bash -c "/home/davidn/bin/ui/wallpaper-startup-set.sh"


exec-once = nmcli dev con wlan0

# It is now integrated in the start via wayland session
# exec-once = bash -c "/home/davidn/bin/sys/gpu-check.sh" >> /tmp/gpu-check-power.log 
