[manager]
border = { fg = "#3b4261", bg = "#1a1b26" }          
current = { fg = "#7aa2f7", bg = "#24283b", bold = true }
hovered = { fg = "#7aa2f7", bg = "#292e42" } 
preview = { fg = "#a9b1d6", bg = "#1a1b26" }  

[status]
overall = { fg = "#545661", bg = "#1a1b26" }  

sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label = { fg = "#7aa2f7", bg = "#1a1b26" }  
progress_normal = { fg = "#3b4261", bg = "#1a1b26" }  
perm_read = { fg = "#e6c384", bg = "#1a1b26" }       

[input]
border = { fg = "#7aa2f7", bg = "#1a1b26" }
fg = "#a9b1d6"
bg = "#1a1b26"

[preview]
border = { fg = "#3b4261", bg = "#1a1b26" }

[shadow]
normal = { fg = "#3b4261", bg = "#1a1b26" }
active = { fg = "#7aa2f7", bg = "#1a1b26" }

