#!/usr/bin/env bash

pkexec env \
    DISPLAY=$DISPLAY \
    XAUTHORITY=$XAUTHORITY \
    WAYLAND_DISPLAY=$WAYLAND_DISPLAY \
    XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
    DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS \
    timeshift-gtk
