[shell.launcher]
app_grid = false
auto_paste = "auto"
categories = true
compact = false
fetch_exchange_rates = true
pinned = []
provider_prefix = "."
show_app_actions = false
show_app_origin_indicator = true
show_icons = true
sort_by_usage = true

[shell.launcher.dmenu]

[shell.launcher.panels]
ignored = [ "polkit", "setup-wizard", "test", "launcher", "wallpaper" ]

# Workarounds like this don't seem to work

[shell.launcher.dmenu.entry.bluetooth]
label = "Bluetooth"
prefix = "bt"
glyph = "bluetooth"
global = false
command = "noctalia msg panel-open control-center bluetooth"
exec = ""

[shell.launcher.dmenu.entry.settings]
label = "Settings"
prefix = "set"
glyph = "settings"
global = false
command = "noctalia msg settings-open"
exec = ""

[shell.launcher.dmenu.entry.power]
label = "Power"
prefix = "pow"
glyph = "power"
global = false
command = "noctalia msg panel-open session"
exec = ""

[shell.launcher.dmenu.entry.wallpaper]
label = "Wallpaper"
prefix = "wal"
glyph = "wallpaper"
global = false
command = "noctalia msg panel-open wallpaper"
exec = ""

[shell.launcher.dmenu.entry.pickers]
label = "Pickers"
prefix = "pk"
glyph = "apps"
global = false
command = "/home/davidn/bin/pickers/center-noctalia.sh --list"
exec = "env PICKER_ENGINE=noctalia /home/davidn/bin/pickers/center-noctalia.sh '{selection}'"
