[location]
address = ""
auto_locate = true
custom_schedule = false
sunrise = ""
sunset = ""

[accessibility]
high_contrast = false
ui_scale = 1.0

[audio]
enable_overdrive = false
enable_sounds = true
sound_theme = "freedesktop"
sound_volume = 0.5

[backdrop]
blur_intensity = 0.5
enabled = false
tint_intensity = 0.30000001192092896

[battery]
warning_threshold = 10

[brightness]
enable_ddcutil = false
ignore_mmids = []
minimum_brightness = 0.0
sync_all_monitors = false

[calendar]
enabled = true
event_date_format = "%A %e %B"
event_time_format = "%H:%M"
refresh_minutes = 15

[calendar.account.personal_principal]
calendars = []
color = "primary"
credential_source = "secret-service"
name = ""
password_file = ""
path = ""
provider = ""
server_url = ""
type = "google"
username = ""

[calendar.reminders]
all_day_digest_time = "09:00"
default_lead_minutes = 10
enabled = true
use_event_reminders = true

[hooks]
battery_charging = []
battery_discharging = []
battery_percentage_changed = []
battery_plugged = []
bluetooth_disabled = []
bluetooth_enabled = []
colors_changed = []
logging_out = []
power_profile_changed = []
rebooting = []
session_locked = []
session_unlocked = []
shutting_down = []
started = []
theme_mode_changed = []
wallpaper_changed = []
wifi_disabled = []
wifi_enabled = []

[hot_corners]
delay_ms = 0
enabled = false

[hot_corners.bottom_left]
action = "none"
command = ""

[hot_corners.bottom_right]
action = "none"
command = ""

[hot_corners.top_left]
action = "none"
command = ""

[hot_corners.top_right]
action = "none"
command = ""

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 2.0

[idle.behavior.lock]
action = "lock"
command = ""
enabled = false
locked_timeout = 0.0
resume_command = ""
timeout = 600.0

[idle.behavior.lock-and-suspend]
action = "lock_and_suspend"
command = ""
enabled = false
locked_timeout = 0.0
resume_command = ""
timeout = 900.0

[idle.behavior.screen-off]
action = "screen_off"
command = ""
enabled = false
locked_timeout = 0.0
resume_command = ""
timeout = 660.0

[lockscreen]
allow_empty_password = false
blur_intensity = 0.5
blurred_desktop = false
edge_smoothness = 0.30000001192092896
enabled = true
fingerprint = true
lock_before_suspend = true
monitors = []
tint_intensity = 0.30000001192092896
transition = [ "fade", "wipe", "disc", "stripes", "zoom", "honeycomb" ]
transition_duration = 1500.0
wallpaper = ""

[nightlight]
enabled = true
force = false
temperature_day = 6500
temperature_night = 4000

[notification]
background_opacity = 0.5
border = true
border_color = "outline"
border_width = 1.0
collapse_on_dismiss = true
enable_daemon = true
follow_focused_output = false
history_retention_hours = 0
keep_dismissed_in_history = true
layer = "overlay"
max_visible = 0
monitors = []
offset_x = 20
offset_y = 8
position = "top_center"
scale = 1.0
show_actions = true
show_app_name = true
width = 500

[osd]
background_opacity = 0.5
border = true
border_color = "outline"
border_width = 1.0
enabled = true
follow_focused_output = false
hide_delay_ms = 1400
monitors = []
offset_x = 20
offset_y = 8
orientation = "horizontal"
position = "top_center"
position_vertical = "top_center"
scale = 1.0

[osd.kinds]
bluetooth = true
brightness = true
caffeine = true
dnd = true
keyboard_backlight = true
keyboard_layout = true
lock_keys = true
media = true
nightlight = true
power_profile = true
privacy = true
volume = true
volume_input = true
volume_output = true
wifi = true

[plugin_settings]

[plugins]
auto_update = "all"
enabled = [ "kenn/keybind-cheatsheet" ]

[[plugins.source]]
enabled = true
kind = "git"
location = "https://github.com/noctalia-dev/official-plugins"
name = "official"

[[plugins.source]]
enabled = true
kind = "git"
location = "https://github.com/noctalia-dev/community-plugins"
name = "community"

[storage]
key_file = ""
key_source = "secret-service"

[system.monitor]
cpu_freq_activity_threshold = 2.5
cpu_freq_critical_threshold = 4.5
cpu_poll_seconds = 2.0
cpu_temp_activity_threshold = 60.0
cpu_temp_critical_threshold = 85.0
cpu_temp_sensor_path = ""
cpu_usage_activity_threshold = 50.0
cpu_usage_critical_threshold = 90.0
disk_free_activity_threshold = 80.0
disk_free_critical_threshold = 95.0
disk_free_pct_activity_threshold = 80.0
disk_free_pct_critical_threshold = 95.0
disk_poll_seconds = 10.0
disk_used_activity_threshold = 80.0
disk_used_critical_threshold = 95.0
disk_used_pct_activity_threshold = 80.0
disk_used_pct_critical_threshold = 95.0
enabled = true
gpu_poll_seconds = 5.0
gpu_temp_activity_threshold = 60.0
gpu_temp_critical_threshold = 85.0
gpu_usage_activity_threshold = 50.0
gpu_usage_critical_threshold = 95.0
gpu_vram_activity_threshold = 50.0
gpu_vram_critical_threshold = 90.0
memory_poll_seconds = 2.0
net_rx_activity_threshold = 1.0
net_rx_critical_threshold = 50.0
net_tx_activity_threshold = 1.0
net_tx_critical_threshold = 50.0
network_poll_seconds = 3.0
ram_pct_activity_threshold = 60.0
ram_pct_critical_threshold = 90.0
swap_pct_activity_threshold = 20.0
swap_pct_critical_threshold = 80.0

[weather]
effects = true
enabled = true
refresh_minutes = 30
unit = "metric"
