input {
    kb_layout = es,us
    kb_options = grp:alt_space_toggle
    follow_mouse = 1
    sensitivity = 0

    touchpad {
        disable_while_typing = true
        natural_scroll = true
    }
}

gesture = 2, right, workspace, +1
gesture = 2, left, workspace, -1

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
