# ────────────── Windowrulev2 cheatsheet ──────────────
# tile                → fuerza modo mosaico (no flotante)
# floa               → fuerza modo flotante
# maximize            → ocupa todo el layout, pero no es fullscreen real
# nofullscreenrequest → ignora peticiones de fullscreen (útil en juegos)
# workspace X         → manda la ventana al workspace X
# center              → centra la ventana (si está flotante)
# size width height   → establece tamaño inicial (si está flotante)
# move x y            → mueve ventana a coordenadas (si está flotante)
# noblur              → desactiva blur para esa ventana
# bordercolor r g b a → color de borde específico
# opacity 0.xx        → opacidad personalizada
# ─────────────────────────────────────────────────────

# General rules
windowrulev2 = suppressevent maximize, class:.* # Ignora eventos de maximización enviados por programas

# Games - Launchers workspace 9
windowrulev2 = workspace 9, class:^(steam)$
windowrulev2 = workspace 9, class:^(heroic|com-atlauncher-App)$

# Games - Games special workspace
windowrulev2 = workspace special:gaming, immediate, class:^(cs2)$
windowrulev2 = workspace special:gaming, fullscreen, class:^(Minecraft.*|steam_app_.*|Katana ZERO)$

# Workspace rules - Terminals
# windowrulev2 = workspace 1, opacity 0.95 0.9, title:^(kitty|foot)$

# Workspace rules - Browsers & productivity apps
windowrulev2 = workspace 1, title:tmux 
windowrulev2 = workspace 2, class:zen
windowrulev2 = workspace 3, class:^(thunar)$
windowrulev2 = workspace 4, class:obsidian
windowrulev2 = workspace 3, class:org.pwmt.zathura
windowrulev2 = workspace 4, class:^(anki|org.musicbrainz.Picard|org.pulseaudio.pavucontrol)$ 
windowrulev2 = workspace 8, class:^(vesktop|discord)$
windowrulev2 = workspace 10, title:rmpc
windowrulev2 = workspace special, class:org.keepassxc.KeePassXC
