# PREFIX
unbind C-b
set -g prefix M-j
bind-key M-j send-prefix

# COPY MODE
set -g mode-keys vi
bind m copy-mode

bind-key -T copy-mode-vi v  send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y  send-keys -X copy-pipe-and-cancel "wl-copy"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U



# RESIZE MODE
resize_handler="~/.config/tmux/bin/tmux-resize-mode.sh"
bind e run-shell "$resize_handler on"

bind -T resize_mode h resize-pane -L 2 \; switch-client -T resize_mode
bind -T resize_mode j resize-pane -D 2 \; switch-client -T resize_mode  
bind -T resize_mode k resize-pane -U 2 \; switch-client -T resize_mode
bind -T resize_mode l resize-pane -R 2 \; switch-client -T resize_mode
bind -T resize_mode H resize-pane -L 10 \; switch-client -T resize_mode
bind -T resize_mode J resize-pane -D 10 \; switch-client -T resize_mode
bind -T resize_mode K resize-pane -U 10 \; switch-client -T resize_mode
bind -T resize_mode L resize-pane -R 10 \; switch-client -T resize_mode

bind -T resize_mode q run-shell "$resize_handler off" 
bind -T resize_mode Escape run-shell "$resize_handler off"

# WORKSPACES
workspace_edit="~/.config/tmux/bin/tmux-workspaces.sh"
bind C run-shell "$workspace_edit open"
bind K run-shell "$workspace_edit close"

bind N switch-client -n
bind P switch-client -p
bind c new-window -c "#{pane_current_path}"

# UTILS
unbind f
bind f run-shell '
    if [ "#{session_name}" = "popup" ]; then
        tmux detach-client
    else
        tmux display-popup -d "#{pane_current_path}" -w 80% -h 80% -E "tmux attach-session -t popup || tmux new-session -s popup fish"
    fi
'

bind r source-file ~/.config/tmux/tmux.conf \; display "✓ Reloaded"

# NAVIGATION (Vim-Tmux Aware) from https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'

bind v split-window -v -c "#{pane_current_path}"
bind h split-window -h -c "#{pane_current_path}"

bind x kill-pane
bind & kill-window
bind q confirm-before -p "Kill session #S? (y/n)" kill-session
