set -g status on
set -g status-position top
set -g status-justify left
set -g status-interval 5
set -g status-left-length 30
set -g status-right-length 50
set -g window-status-separator ""
set -gw automatic-rename off

set -g status-style "bg=default,fg=default"
set -g window-status-style "bg=default"
set -g window-status-current-style "bg=default"
set -g mode-style "bg=default,fg=colour4,underscore"

set -g window-status-format         "#[bg=default,fg=colour8] ● "
set -g window-status-current-format "#[bg=default,fg=#{?#{||:#{client_prefix},#{pane_in_mode}},colour3,colour4},bold] ● "
