# Tmux theme - Omarchy style

set -g status on
set -g status-position top
set -g status-interval 5
set -g status-left-length 30
set -g status-right-length 50
set -g window-status-separator ""
set -gw automatic-rename on
set -gw automatic-rename-format '#{pane_current_command}'

set -g status-style "bg=default,fg=default"
set -g status-left "#[fg=colour0,bg=colour4,bold] #S #[bg=default] "
set -g status-right "#[fg=colour4,bold]#{?pane_in_mode,COPY ,}#{?client_prefix,PREFIX ,}#[fg=colour8,bold]#h "
set -g status-justify left
set -g window-status-format "#[fg=colour8] #I:#W "
set -g window-status-current-format "#[fg=colour4,bold] #I:#W "

set -g pane-border-style "fg=colour8"
set -g pane-active-border-style "fg=colour4"
set -g message-style "bg=default,fg=colour4"
set -g message-command-style "bg=default,fg=colour4"
set -g mode-style "bg=colour4,fg=colour0"
setw -g clock-mode-colour colour4
